//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.RRHH.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ddRRHHEntities : DbContext
    {
        public ddRRHHEntities()
            : base("name=ddRRHHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<empleado> empleadoes { get; set; }
        public virtual DbSet<empleado_empleo> empleado_empleo { get; set; }
        public virtual DbSet<empleo> empleos { get; set; }
    }
}
