//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.RRHH.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado_empleo
    {
        public int codigo_empleado { get; set; }
        public int codigo_empleo { get; set; }
        public int codigo_area { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_final { get; set; }
        public bool activo { get; set; }
    
        public virtual area area { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual empleo empleo { get; set; }
    }
}
