//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.RRHH.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleo()
        {
            this.empleado_empleo = new HashSet<empleado_empleo>();
        }
    
        public int codigo { get; set; }
        public string nombre { get; set; }
        public decimal salario_minimo { get; set; }
        public decimal salario_maximo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado_empleo> empleado_empleo { get; set; }
    }
}
